import type { CaseStudy } from "@/types";

const realResults = [
  "Built a 35-minute exosomes course",
  "Delivered 70+ students to Engr. Khuzama Tahir",
  "Managing the social media page of an Islamic tutor",
];

export const caseStudies: CaseStudy[] = [
  {
    id: "nova-rebrand",
    slug: "nova-rebrand",
    title: "Nova Tech Complete Rebrand",
    client: "Nova Technologies",
    category: "Branding",
    tags: ["Brand Strategy", "Visual Identity", "Web Design"],
    description: "A complete brand overhaul that repositioned Nova from a generic tech company to an industry-leading innovator.",
    challenge: "Nova Technologies had grown rapidly but their brand felt disconnected from their premium positioning. They needed a cohesive identity that reflected their innovative culture.",
    solution: "We developed a comprehensive brand strategy starting with stakeholder interviews and competitive analysis. The new identity system included a refined logo, bold color palette, and distinctive visual language.",
    results: realResults,
    heroImage: "/images/placeholder.jpg",
    gallery: ["/images/placeholder.jpg", "/images/placeholder.jpg"],
    featured: true,
    year: 2024,
  },
  {
    id: "growthco-ads",
    slug: "growthco-ads",
    title: "GrowthCo Performance Campaign",
    client: "GrowthCo",
    category: "Performance Marketing",
    tags: ["Google Ads", "Meta Ads", "CRO"],
    description: "A 6-month performance marketing campaign that tripled GrowthCo's revenue through strategic paid media.",
    challenge: "GrowthCo was spending $50k/month on ads with a 1.2x ROAS. They needed dramatic improvements in efficiency and scale.",
    solution: "We audited their entire funnel, rebuilt campaign structures from scratch, and implemented advanced audience segmentation with dynamic creative optimization.",
    results: realResults,
    heroImage: "/images/placeholder.jpg",
    gallery: ["/images/placeholder.jpg"],
    featured: true,
    year: 2024,
  },
  {
    id: "brandx-website",
    slug: "brandx-website",
    title: "BrandX E-commerce Platform",
    client: "BrandX",
    category: "Web Design & Development",
    tags: ["E-commerce", "Next.js", "UX Design"],
    description: "A stunning e-commerce experience built for conversion, resulting in a 180% lift in online sales.",
    challenge: "BrandX had a dated website with poor mobile experience and a 3.2% conversion rate that was dragging down their overall revenue.",
    solution: "We redesigned the entire shopping experience with a mobile-first approach, implemented advanced product discovery features, and optimized the checkout flow.",
    results: realResults,
    heroImage: "/images/placeholder.jpg",
    gallery: ["/images/placeholder.jpg", "/images/placeholder.jpg"],
    featured: true,
    year: 2023,
  },
  {
    id: "scaleup-content",
    slug: "scaleup-content",
    title: "ScaleUp Content Engine",
    client: "ScaleUp",
    category: "Content & Creative",
    tags: ["SEO Content", "Social Media", "Video"],
    description: "A comprehensive content strategy that established ScaleUp as the thought leader in their niche.",
    challenge: "ScaleUp had zero organic presence and was entirely dependent on paid channels. They needed a sustainable content engine.",
    solution: "We built a full content strategy including SEO-optimized blog content, LinkedIn thought leadership, and a video series.",
    results: realResults,
    heroImage: "/images/placeholder.jpg",
    gallery: ["/images/placeholder.jpg"],
    featured: false,
    year: 2023,
  },
];
